language: ruby
os:
  - osx
before_install:
  - gem install bundler
gemfile:
  - Gemfile
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
script:
  - bundle exec rspec spec
