language: ruby
before_install:
  - gem install bundler
gemfile:
  - Gemfile
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
script:
  - bundle exec rspec spec
